import { apiUrl, request } from "./client.js";

export const teacherApi = {
  dashboard: () => request("/teacher/dashboard"),
  classes: () => request("/teacher/classes"),
  students: (query = "") => request(`/teacher/students${query}`),
  resources: () => request("/teacher/resources"),
  uploadResource: (body) => request("/teacher/resources", { method: "POST", body }),
  deleteResource: (id) => request(`/teacher/resources/${id}`, { method: "DELETE" }),
  subjects: () => request("/teacher/subjects"),
  knowledgePoints: (query = "") => request(`/teacher/knowledge-points${query}`),
  createKnowledgePoint: (body) => request("/teacher/knowledge-points", { method: "POST", body }),
  updateKnowledgePoint: (id, body) => request(`/teacher/knowledge-points/${id}`, { method: "PUT", body }),
  deleteKnowledgePoint: (id) => request(`/teacher/knowledge-points/${id}`, { method: "DELETE" }),
  mergeKnowledgePoint: (id, targetId) => request(`/teacher/knowledge-points/${id}/merge`, { method: "POST", body: { targetId } }),
  questions: (query = "") => request(`/teacher/questions${query}`),
  createQuestion: (body) => request("/teacher/questions", { method: "POST", body }),
  updateQuestion: (id, body) => request(`/teacher/questions/${id}`, { method: "PUT", body }),
  deleteQuestion: (id) => request(`/teacher/questions/${id}`, { method: "DELETE" }),
  copyQuestion: (id) => request(`/teacher/questions/${id}/copy`, { method: "POST" }),
  previewQuestionImport: (body) => request("/teacher/questions/import-preview", { method: "POST", body }),
  importQuestions: (rows) => request("/teacher/questions/import", { method: "POST", body: { rows } }),
  questionImportTemplateUrl: () => apiUrl("/teacher/question-import-template"),
  assignments: () => request("/teacher/assignments"),
  createAssignment: (body) => request("/teacher/assignments", { method: "POST", body }),
  submissions: (query = "") => request(`/teacher/submissions${query}`),
  gradeSubmission: (id, body) => request(`/teacher/submissions/${id}/grade`, { method: "PUT", body }),
  analytics: () => request("/teacher/analytics"),
  notices: () => request("/teacher/notices"),
  createNotice: (body) => request("/teacher/notices", { method: "POST", body }),
};
